version: '3.3'

services:
  idporten-bankid-mobil:
    image: ${REGISTRY}/idporten-bankidmobil:${VERSION}
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
      - 5008:5008
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  web:
    image: eid-jenkins02.dmz.local:8082/web:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 443
    networks:
      atest:
        aliases:
          - eid-atest-web01.dmz.local
          - eid-inttest-web01.dmz.local
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-admin:
    image: eid-jenkins02.dmz.local:8081/idporten-admin:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
        aliases:
          - eid-atest-admin01.dmz.local
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  testsp-saml:
    image:  eid-jenkins02.dmz.local:8081/testsp-saml:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  activemq:
    image:  rmohr/activemq:5.11.1
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 61616
      - 8161
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  selenium:
    image: selenium/standalone-firefox:3.14.0-europium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444
    networks:
      atest:
        aliases:
          - selenium_host
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  eventlog-db:
    image:  eid-jenkins02.dmz.local:8081/eventlog-db:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
networks:
  atest:
    driver: overlay
    attachable: true
configs:
  log_config:
    file: ./log_config
